## YAML Template.
server:
  port: 8888
spring: 
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: file:///C:/cruiz/configuraciones
         

              
          